- src:     elao.env
  version: 1.0
- src:     elao.apt
  version: 1.0
  version: 1.0
- src:     elao.files
  version: 1.0
- src:     elao.nodejs
  version: 1.0
- src:     elao.npm
  version: 1.0
- src:     elao.php
  version: 1.0
- src:     elao.composer
  version: 1.0
- src:     elao.nginx
  version: 1.0
